services:
  db:
    image: postgres:16-alpine
    container_name: life-care-db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: life_care_plus
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - life-care-network
  redis:
    image: redis:7-alpine
    container_name: life-care-redis
    restart: always
    ports:
      - "6380:6379"
    networks:
      - life-care-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: life-care-backend
    restart: always
    command: npm run dev
    ports:
      - "5000:5000"
      - "5555:5555"
    env_file:
      - ./server/.env
    depends_on:
      - db
      - redis
    volumes:
      - ./server:/app
      - /app/node_modules
      - backend_logs:/app/logs
    networks:
      - life-care-network

  # frontend:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   container_name: life-care-frontend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   env_file:
  #     - ./client/.env.local
  #   environment:
  #     - WATCHPACK_POLLING=true
  #   depends_on:
  #     - backend
  #     - redis
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules
  #   networks:
  #     - life-care-network

volumes:
  postgres_data:
  backend_logs:

networks:
  life-care-network:
    driver: bridge
